# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53ad5a211b8ab996cb66a83e9e8fe961d3ca8fdb8ef56b77dcd3ab33c80fe7c111cda6d30cc3acfeaaa0ef172752b29e79b971c2475840a87c2ff486138d8bff

test:
  secret_key_base: ffca34636d97e27a3efe15d4f5741989b2c30e2c4c6bd5e67517f47a986d8df44832b1807cef46b64b79bae5b3a75f53247f0f62277f9f18f26dc72a045d2b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
